apiVersion: apps/v1
kind: Deployment
metadata:
  name: stk-deployment
  labels:
    app: stk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stk
  template:
    metadata:
      labels:
        app: stk
    spec:
        volumes:
        - name: stk-assets
          hostPath:
           path: /SuperTuxKart.app/Contents/Resources/data
      containers:
      - name: stk-server
        image: 742301976366.dkr.ecr.us-east-2.amazonaws.com/stk-server:latest
        command: ['sh', '-c', '/usr/local/bin/supertuxkart']